apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  NODE_ENV: "production"
  GOOGLE_SHEET_ID: "dummy-google-sheet-id"
  GOOGLE_SERVICE_ACCOUNT_EMAIL: "dummy-service-account@dummy-project.iam.gserviceaccount.com"
