apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  NODE_ENV: "production"
  GOOGLE_SHEET_ID: "1z-Jx7QuO1nwXH5k0BKPEJNE8QivBtNEqdHf-YEHN2hs"
  GOOGLE_SERVICE_ACCOUNT_EMAIL: "vishal-tour-and-travelers@civil-authority-488609-k1.iam.gserviceaccount.com"
